// Get the form
const mealForm = document.getElementById("mealForm");

// Get the meal plan area
const mealPlan = document.getElementById("mealPlan");


// When the user clicks Generate Meal Plan
mealForm.addEventListener("submit", function(event) {

    // Stop the page from refreshing
    event.preventDefault();


    // Collect user data
    const userData = {

        age: document.getElementById("age").value,

        weight: document.getElementById("weight").value,

        height: document.getElementById("height").value,

        goal: document.getElementById("goal").value,

        diet: document.getElementById("diet").value,

        allergies: document.getElementById("allergies").value,

        calories: document.getElementById("calories").value,

        meals: document.getElementById("meals").value
    };


    // Display the collected data in console
    console.log(userData);


    // Temporary meal plan
    mealPlan.innerHTML = `

        <div class="meal">
            <h3>🌅 Breakfast</h3>
            <p>Meal will be generated by AI.</p>
            <p>Calories: 500 kcal</p>
            <p>Protein: 20 g</p>
        </div>

        <div class="meal">
            <h3>🍛 Lunch</h3>
            <p>Meal will be generated by AI.</p>
            <p>Calories: 700 kcal</p>
            <p>Protein: 30 g</p>
        </div>

        <div class="meal">
            <h3>🥜 Snack</h3>
            <p>Meal will be generated by AI.</p>
            <p>Calories: 300 kcal</p>
            <p>Protein: 10 g</p>
        </div>

        <div class="meal">
            <h3>🌙 Dinner</h3>
            <p>Meal will be generated by AI.</p>
            <p>Calories: 600 kcal</p>
            <p>Protein: 25 g</p>
        </div>

    `;
});